<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<NoWarn>CS8600;CS8601;CS8602;CS8603;CS8604;CS0168;CS0219</NoWarn>
		<DebugType Condition="'$(Configuration)'=='Release'">none</DebugType>
		<DebugSymbols Condition="'$(Configuration)'=='Release'">false</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<!-- Email transport -->
		<PackageReference Include="MailKit" Version="4.15.1" />
		<PackageReference Include="MimeKit" Version="4.15.1" />

		<!-- Cryptography -->
		<PackageReference Include="PgpCore" Version="6.5.0" />

		<!-- Database -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<!-- JSON -->

		<!-- Logging -->
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
	</ItemGroup>

</Project>