version: '3.8'
services:

  echat-web:
    restart: unless-stopped
    image: ghcr.io/rsvln/echatweb:latest
    container_name: echat
    privileged: true
    volumes:
      - /srv/md0/echat/data:/app/data
    ports:
      - 9999:8080
