namespace EChat.Core.Models;

/// <summary>
/// One-time invite token generated by a user and shared out-of-band.
/// Only the SHA-256 hash is stored — the plaintext token is shown once and never persisted.
/// </summary>
public class PendingInvite
{
    public string TokenId { get; set; } = Guid.NewGuid().ToString();

    /// <summary>SHA-256(rawToken), hex-encoded lower-case. Used for lookup without storing the secret.</summary>
    public string TokenHash { get; set; } = string.Empty;

    /// <summary>Account that generated this invite.</summary>
    public string AccountId { get; set; } = string.Empty;

    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>After this time the token is rejected even if unused.</summary>
    public DateTimeOffset ExpiresAt { get; set; }

    /// <summary>Null = not yet used. Set = burned (one-time).</summary>
    public DateTimeOffset? UsedAt { get; set; }

    /// <summary>Optional human-readable label shown in the pending-invites list ("for Bob").</summary>
    public string? Label { get; set; }
}
