// <auto-generated />
using System;
using EChat.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EChat.Core.Data.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20260504055434_AddContactManagementFields")]
    partial class AddContactManagementFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("EChat.Core.Models.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarColor")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImapPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImapServer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImapUseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InviteToken")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SmtpUseSsl")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("EChat.Core.Models.Attachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("EChat.Core.Models.Chat", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastMessageId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Muted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingOutgoingInviteToken")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TombstoneVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ContactEmail");

                    b.HasIndex("GroupId");

                    b.HasIndex("LastActivityAt");

                    b.HasIndex("AccountId", "ContactEmail");

                    b.HasIndex("Archived", "LastActivityAt");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("EChat.Core.Models.ChatGroup", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId");

                    b.HasIndex("Version");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("EChat.Core.Models.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ClockSkewDetected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DisplayTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("EditVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Encrypted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FormattedContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImapFolder")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ImapUid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InReplyTo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("Sender");

                    b.HasIndex("ChatId", "Timestamp");

                    b.HasIndex("MessageId", "ChatId")
                        .IsUnique();

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("EChat.Core.Models.Contact", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("BlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LocalKeyRevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPrivateKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPublicKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsBatching")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER");

                    b.HasKey("Email");

                    b.HasIndex("Verified");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("EChat.Core.Models.GroupKeyPair", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.HasIndex("Fingerprint");

                    b.ToTable("GroupKeyPairs");
                });

            modelBuilder.Entity("EChat.Core.Models.GroupMember", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberEmail")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameColor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId", "MemberEmail");

                    b.HasIndex("MemberEmail");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("EChat.Core.Models.ImapFolderSyncState", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("LastSyncedUid")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("UidValidity")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "FolderName");

                    b.ToTable("ImapFolderStates");
                });

            modelBuilder.Entity("EChat.Core.Models.MessageReaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("MessageId", "Emoji", "Sender");

                    b.ToTable("MessageReactions");
                });

            modelBuilder.Entity("EChat.Core.Models.PendingInvite", b =>
                {
                    b.Property<string>("TokenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AccountId", "UsedAt", "ExpiresAt");

                    b.ToTable("PendingInvites");
                });

            modelBuilder.Entity("EChat.Core.Models.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("EChat.Core.Models.Chat", b =>
                {
                    b.HasOne("EChat.Core.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactEmail")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EChat.Core.Models.ChatGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Contact");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("EChat.Core.Models.ChatMessage", b =>
                {
                    b.HasOne("EChat.Core.Models.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("EChat.Core.Models.GroupMember", b =>
                {
                    b.HasOne("EChat.Core.Models.ChatGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("EChat.Core.Models.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("EChat.Core.Models.ChatGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
