// <auto-generated />
using System;
using EChat.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EChat.Core.Data.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20260331020000_AddMessageStatus")]
    partial class AddMessageStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("EChat.Core.Models.ChatMessage", b =>
                {
                    b.Property<string>("Id").HasColumnType("TEXT");
                    b.Property<string>("AttachmentPath").HasColumnType("TEXT");
                    b.Property<string>("ChatId").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("ClockSkewDetected").HasColumnType("INTEGER");
                    b.Property<string>("Content").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTimeOffset>("DisplayTimestamp").HasColumnType("TEXT");
                    b.Property<int>("EditVersion").HasColumnType("INTEGER");
                    b.Property<bool>("Encrypted").HasColumnType("INTEGER");
                    b.Property<string>("InReplyTo").HasColumnType("TEXT");
                    b.Property<bool>("IsEdited").HasColumnType("INTEGER");
                    b.Property<string>("MessageId").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTimeOffset>("ReceivedAt").HasColumnType("TEXT");
                    b.Property<string>("Sender").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Status").HasColumnType("INTEGER");
                    b.Property<DateTimeOffset>("Timestamp").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("MessageId");
                    b.HasIndex("Sender");
                    b.HasIndex("ChatId", "Timestamp");
                    b.HasIndex("MessageId", "ChatId").IsUnique();
                    b.ToTable("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
